fs/cifs - add ZFS ACL support to SMB client
truenas/linux pull request #144
Opened 2023-12-21 13:18 UTC by anodos325

Add an xattr handler with same namespace as ZFS ACL xattr handler to allow userspace utilities to easily preserve and convert contents of SMB Security Descriptor DACL into native ZFS ACL when ingesting data during migration via SMB client (for example using rsync with the explicit option to preserve the xattr in question).

This PR also adds a new procfs endpoint:
/proc/fs/cifs/zfsacl_configuration_options that can be used to control error handling for cases where we can't convert SID into a Unix ID, and currently also whether we allow setting NT ACL via xattr writes on remote SMB server (disabled by default).

2023-12-21 13:18 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122619

2023-12-21 13:37 UTC, anodos325 commented
Rebase of PR https://github.com/truenas/linux/pull/110

2023-12-21 21:28 UTC, bmeagherix requested changes

2023-12-21 21:28 UTC, bmeagherix commented on fs/smb/client/cifsacl.c
> + */
Maybe add a comment about the return value.

It appears that we have 3 states:

- `< 0`: error
- `> 0`: success
- `== 0`: upcall required

Is that correct?

2023-12-21 21:28 UTC, bmeagherix commented on fs/smb/client/cifsacl.c
> +			return -ENOMEM;
`kfree(sidstr)` required?

2023-12-22 03:37 UTC, bmeagherix approved these changes

2023-12-26 18:44 UTC, ixhamza commented on fs/smb/client/cifs_debug.c
> +		return -EFAULT;
`EINVAL` looks more reasonable.

2023-12-26 18:44 UTC, ixhamza commented on fs/smb/client/cifs_debug.c
> +	char flags_string[12] = { 0 };
Considering that `MODFLAG_ALL_IDMAP` is only half a byte, perhaps we could reduce `flags_string`.

2023-12-28 13:08 UTC, ixhamza approved these changes

2023-12-28 14:52 UTC, usaleem-ix approved these changes

2023-12-29 16:03 UTC, merged

2023-12-29 16:03 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.