Change CONFIG_CONSOLE_LOGLEVEL_DEFAULT to 6 for production build
truenas/linux pull request #157
Opened 2024-02-14 15:28 UTC by bmeagherix

Currently `CONFIG_CONSOLE_LOGLEVEL_DEFAULT` has been set to 7.  This means that [KERN_DEBUG](https://www.kernel.org/doc/html/next/core-api/printk-basics.html) messages will be echoed to the console.  (This results in SCST being particularly noisy on the console.)

This PR drops the default to 6 (i.e. KERN_INFO) for production builds, but keeps it at 7 for the debug kernel.

At run time, the current value can always be changed by e.g.
```
# echo 6 > /proc/sys/kernel/printk
```

2024-02-14 15:29 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127361

2024-02-14 15:29 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127361

2024-02-14 15:41 UTC, usaleem-ix requested changes
@bmeagherix `debian_am64.config` is the default config coming from Debian that we usually don't modify at all. There is `tn-production.config`, which contains production kernel config options that are not Debian default. I think we can reduce the loglevel from `tn-production.config` and let the `tn-debug.config` remain as is, so debug kernel has Debian default loglevel.

2024-02-14 15:52 UTC, usaleem-ix approved these changes

2024-02-14 16:59 UTC, ixhamza approved these changes
It seems that SCST allows us to change the log level in their module as well. I wonder what log level we are using for TrueNAS production build and if we also need to adjust the log level there. [11. Debugging and troubleshooting](https://scst.sourceforge.net/scst_pg.html).

2024-02-15 01:13 UTC, merged

2024-02-15 01:14 UTC, bugclerk commented
Not updating JIRA ticket https://ixsystems.atlassian.net/browse/NAS-127361 target versions as no JIRA version corresponds to this PR

2024-02-15 01:14 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.

2024-02-15 01:18 UTC, bmeagherix commented
> It seems that SCST allows us to change the log level in their module as well. I wonder what log level we are using for TrueNAS production build and if we also need to adjust the log level there. [11. Debugging and troubleshooting](https://scst.sourceforge.net/scst_pg.html).

I checked [build.manifest](https://github.com/truenas/scale-build/blob/master/conf/build.manifest) is using `make 2perf` and `make 2debug` respectively, but I agree it may warrant a 2nd look to ensure this is taking effect.